translations = {
    "tr": {
        "login": "Giriş Yap",
        "logout": "Çıkış Yap",
        "dashboard": "Panel",
        "username": "Kullanıcı Adı",
        "password": "Şifre",
        "flight_number": "Uçuş Numarası",
        "add_flight": "Yeni Uçuş Ekle",
        "save": "Kaydet",
        "cancel": "İptal",
        "role": "Rol",
        "admin": "Admin",
        "pilot": "Pilot",
        "copilot": "Copilot",
        "technician": "Teknisyen",
        "error_blank": "Bu alan boş bırakılamaz.",
        "success_user_created": "Kullanıcı başarıyla oluşturuldu.",
        "new_user": "Yeni Kullanıcı",
        "reports": "Raporlar",
        "crew_reports": "Ekip Raporları",
        "flights": "Uçuşlar",
        "home": "Anasayfa"
    },
    "en": {
        "login": "Login",
        "logout": "Logout",
        "dashboard": "Dashboard",
        "username": "Username",
        "password": "Password",
        "flight_number": "Flight Number",
        "add_flight": "Add New Flight",
        "save": "Save",
        "cancel": "Cancel",
        "role": "Role",
        "admin": "Admin",
        "pilot": "Pilot",
        "copilot": "Copilot",
        "technician": "Technician",
        "error_blank": "This field cannot be left blank.",
        "success_user_created": "User created successfully.",
        "new_user": "New User",
        "reports": "Reports",
        "crew_reports": "Crew Reports",
        "flights": "Flights",
        "home": "Home"
    }
}